import {
  CircleAlert,
  CircleCheck,
  Clock,
  Handshake,
  Lightbulb,
  ListChecks,
  MessageSquareQuote,
  OctagonAlert,
  Sparkles,
  TrendingUp,
  Users,
} from 'lucide-react'
import clsx from 'clsx'
import type { LucideIcon } from 'lucide-react'
import {
  Badge,
  DEAL_STAGES,
  DEAL_STAGE_LABEL,
  DealStageBadge,
  HealthBadge,
  PriorityBadge,
} from '@/components/ui/Badge'
import { SectionTitle } from '@/components/ui/Misc'
import { dateOnly, dueLabel, daysUntil, money, relTime } from '@/lib/format'
import type { Deal, DealHighlight, DealNextStep } from '@/lib/types'

/**
 * The Closer surface for a contact whose first meeting already happened: the
 * commercial shape of the deal, the key highlights the analysis surfaced, and
 * the ranked next steps to close it.
 *
 * Meetings themselves live on the contact's own Meetings tab.
 */
export function DealPanel({
  deal,
  onOpenMeetings,
}: {
  deal: Deal
  onOpenMeetings?: () => void
}) {
  return (
    <div className="space-y-5">
      <DealHeader deal={deal} onOpenMeetings={onOpenMeetings} />
      <NextStepsView deal={deal} />

      <p className="flex items-start gap-1.5 border-t border-hairline pt-3 text-2xs leading-relaxed text-gray-400">
        <Sparkles size={12} className="mt-0.5 shrink-0" />
        Highlights and next steps are generated by Closer from the meeting notes and
        thread history.
      </p>
    </div>
  )
}

// --------------------------------------------------------------------------- //
// Header — stage rail + the numbers that matter
// --------------------------------------------------------------------------- //

function DealHeader({ deal, onOpenMeetings }: { deal: Deal; onOpenMeetings?: () => void }) {
  const lost = deal.stage === 'closed_lost'
  const currentIdx = DEAL_STAGES.indexOf(deal.stage as (typeof DEAL_STAGES)[number])
  const close = daysUntil(deal.expected_close)

  return (
    <div className="rounded-md border border-hairline bg-white p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-2">
          <DealStageBadge stage={deal.stage} />
          <HealthBadge health={deal.health} />
        </div>
        <div className="text-right">
          <div className="text-xl font-bold leading-none text-gray-900 tnum">
            {money(deal.value_usd)}
          </div>
          <div className="mt-1 text-2xs text-gray-500">annual value</div>
        </div>
      </div>

      {/* Stage rail */}
      {!lost ? (
        <div className="mt-4 flex gap-1">
          {DEAL_STAGES.map((s, i) => (
            <div key={s} className="min-w-0 flex-1">
              <div
                className={clsx(
                  'h-1.5 rounded-full',
                  i < currentIdx ? 'bg-brand-600' : i === currentIdx ? 'bg-brand-500' : 'bg-gray-100',
                )}
              />
              <div
                className={clsx(
                  'mt-1.5 truncate text-[10px] leading-tight',
                  i === currentIdx ? 'font-semibold text-gray-800' : 'text-gray-400',
                )}
              >
                {DEAL_STAGE_LABEL[s]}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="mt-4 rounded-sm bg-danger-bg px-3 py-2 text-xs text-danger-text">
          This deal was closed lost.
        </div>
      )}

      <div className="mt-4 grid grid-cols-3 gap-3 border-t border-hairline pt-3">
        <Fact label="Win probability" value={`${deal.probability}%`} />
        <Fact
          label="Expected close"
          value={deal.expected_close ? dateOnly(deal.expected_close) : '—'}
          tone={close !== null && close < 0 ? 'danger' : undefined}
        />
        <Fact label="Owner" value={deal.owner || '—'} />
      </div>

      {deal.summary && (
        <div className="mt-3 rounded-sm bg-sunken p-3">
          <div className="mb-1.5 flex items-center gap-1.5 text-2xs font-semibold uppercase tracking-[0.04em] text-gray-500">
            <Sparkles size={11} /> Where it stands
          </div>
          <p className="text-sm leading-relaxed text-gray-700">{deal.summary}</p>
        </div>
      )}

      <div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-1 text-2xs text-gray-500">
        <span className="inline-flex items-center gap-1">
          <Handshake size={12} /> Opened {relTime(deal.opened_at)}
        </span>
        <span className="inline-flex items-center gap-1">
          <Clock size={12} /> Last activity {relTime(deal.last_activity_at)}
        </span>
        <span className="capitalize">via {deal.source_channel}</span>
        {onOpenMeetings && (
          <button
            onClick={onOpenMeetings}
            className="ml-auto font-medium text-brand-600 hover:underline"
          >
            {deal.meeting_count} {deal.meeting_count === 1 ? 'meeting' : 'meetings'} held →
          </button>
        )}
      </div>
    </div>
  )
}

function Fact({
  label,
  value,
  tone,
}: {
  label: string
  value: string
  tone?: 'danger'
}) {
  return (
    <div>
      <div className="text-2xs uppercase tracking-[0.04em] text-gray-500">{label}</div>
      <div
        className={clsx(
          'mt-0.5 truncate text-sm font-semibold tnum',
          tone === 'danger' ? 'text-danger-text' : 'text-gray-900',
        )}
      >
        {value}
      </div>
    </div>
  )
}

// --------------------------------------------------------------------------- //
// Next steps — highlights first, then the ranked actions
// --------------------------------------------------------------------------- //

const HIGHLIGHT_CFG: Record<string, { icon: LucideIcon; label: string; cls: string }> = {
  strength: { icon: TrendingUp, label: 'Strength', cls: 'text-success-text bg-success-bg' },
  risk: { icon: CircleAlert, label: 'Risk', cls: 'text-warning-text bg-warning-bg' },
  blocker: { icon: OctagonAlert, label: 'Blocker', cls: 'text-danger-text bg-danger-bg' },
  signal: { icon: Lightbulb, label: 'Signal', cls: 'text-info-text bg-info-bg' },
}

const HIGHLIGHT_ORDER = ['blocker', 'risk', 'strength', 'signal']

function NextStepsView({ deal }: { deal: Deal }) {
  const highlights = [...deal.highlights].sort(
    (a, b) =>
      HIGHLIGHT_ORDER.indexOf(a.kind) - HIGHLIGHT_ORDER.indexOf(b.kind) ||
      b.confidence - a.confidence,
  )
  const open = deal.next_steps.filter((s) => s.status !== 'done')
  const done = deal.next_steps.filter((s) => s.status === 'done')

  return (
    <div className="space-y-6">
      <section>
        <SectionTitle right={<span className="text-2xs text-gray-400">{highlights.length}</span>}>
          Key highlights
        </SectionTitle>
        {highlights.length === 0 ? (
          <p className="text-sm text-gray-400">Nothing surfaced yet.</p>
        ) : (
          <div className="space-y-1.5">
            {highlights.map((h) => (
              <HighlightRow key={h.id} highlight={h} />
            ))}
          </div>
        )}
      </section>

      <section>
        <SectionTitle
          right={
            <span className="inline-flex items-center gap-1 text-2xs text-gray-400">
              <ListChecks size={12} /> {open.length} open
            </span>
          }
        >
          Recommended next steps
        </SectionTitle>
        {open.length === 0 ? (
          <p className="text-sm text-gray-400">No open steps — everything recommended is done.</p>
        ) : (
          <div className="space-y-2">
            {open.map((s) => (
              <NextStepCard key={s.id} step={s} />
            ))}
          </div>
        )}
      </section>

      {done.length > 0 && (
        <section>
          <SectionTitle>Completed</SectionTitle>
          <div className="space-y-1">
            {done.map((s) => (
              <div key={s.id} className="flex items-start gap-2 px-1 py-1.5">
                <CircleCheck size={14} className="mt-0.5 shrink-0 text-success" />
                <div className="min-w-0 flex-1">
                  <div className="text-sm text-gray-500 line-through">{s.title}</div>
                  <div className="text-2xs text-gray-400">
                    {s.owner} · {s.due_date ? dateOnly(s.due_date) : '—'}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  )
}

function HighlightRow({ highlight: h }: { highlight: DealHighlight }) {
  const cfg = HIGHLIGHT_CFG[h.kind] ?? HIGHLIGHT_CFG.signal
  const Icon = cfg.icon
  return (
    <div className="flex items-start gap-2.5 rounded-sm border border-hairline px-2.5 py-2">
      <span className={clsx('mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full', cfg.cls)}>
        <Icon size={12} />
      </span>
      <div className="min-w-0 flex-1">
        <p className="text-sm leading-snug text-gray-700">{h.text}</p>
        <div className="mt-0.5 flex items-center gap-2 text-2xs text-gray-400">
          <span className="font-medium uppercase tracking-[0.04em]">{cfg.label}</span>
          <span>·</span>
          <span className="tnum">{Math.round(h.confidence * 100)}% confidence</span>
        </div>
      </div>
    </div>
  )
}

function NextStepCard({ step }: { step: DealNextStep }) {
  const overdue = (daysUntil(step.due_date) ?? 1) < 0
  const blocked = step.status === 'blocked'
  return (
    <div className="rounded-md border border-hairline p-3">
      <div className="flex items-start gap-2.5">
        <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-gray-100 text-2xs font-semibold text-gray-600 tnum">
          {step.step_order}
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex items-start justify-between gap-2">
            <span className="text-sm font-semibold leading-snug text-gray-900">{step.title}</span>
            <PriorityBadge priority={step.priority} />
          </div>
          <p className="mt-1 text-sm leading-relaxed text-gray-600">{step.detail}</p>

          {step.rationale && (
            <div className="mt-2 flex items-start gap-1.5 rounded-sm bg-sunken px-2 py-1.5">
              <MessageSquareQuote size={11} className="mt-0.5 shrink-0 text-gray-400" />
              <span className="text-2xs leading-relaxed text-gray-500">{step.rationale}</span>
            </div>
          )}

          <div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-2xs">
            <span className="inline-flex items-center gap-1 text-gray-500">
              <Users size={11} /> {step.owner}
            </span>
            <span
              className={clsx(
                'inline-flex items-center gap-1',
                overdue ? 'font-medium text-danger-text' : 'text-gray-500',
              )}
            >
              <Clock size={11} /> {dueLabel(step.due_date)}
            </span>
            {blocked && <Badge tone="danger">Blocked</Badge>}
          </div>
        </div>
      </div>
    </div>
  )
}

